#!/bin/zsh
set -euo pipefail

cd "$(dirname "$0")"

FRESHWEB_RUN_LOCK_DIR=${FRESHWEB_RUN_LOCK_DIR:-/tmp/freshweb-live-preview.lock}

terminate_existing_freshweb_runs() {
  local current_pid="$$"
  local parent_pid="$PPID"
  local candidate_pid

  for candidate_pid in $(pgrep -f 'MIX-again-freshweb|freshweb\.js|shorty-book/freshweb\.js' || true); do
    if [[ "$candidate_pid" == "$current_pid" || "$candidate_pid" == "$parent_pid" ]]; then
      continue
    fi
    kill "$candidate_pid" 2>/dev/null || true
  done
}

cleanup_freshweb_lock() {
  rm -rf "$FRESHWEB_RUN_LOCK_DIR" 2>/dev/null || true
}

acquire_freshweb_lock() {
  local existing_pid=""

  if mkdir "$FRESHWEB_RUN_LOCK_DIR" 2>/dev/null; then
    printf '%s\n' "$$" > "$FRESHWEB_RUN_LOCK_DIR/pid"
    return 0
  fi

  if [[ -f "$FRESHWEB_RUN_LOCK_DIR/pid" ]]; then
    existing_pid="$(cat "$FRESHWEB_RUN_LOCK_DIR/pid" 2>/dev/null || true)"
  fi

  if [[ -n "$existing_pid" ]] && kill -0 "$existing_pid" 2>/dev/null; then
    kill "$existing_pid" 2>/dev/null || true
    sleep 1
  fi

  rm -rf "$FRESHWEB_RUN_LOCK_DIR" 2>/dev/null || true
  mkdir "$FRESHWEB_RUN_LOCK_DIR"
  printf '%s\n' "$$" > "$FRESHWEB_RUN_LOCK_DIR/pid"
}

terminate_existing_freshweb_runs
acquire_freshweb_lock
trap cleanup_freshweb_lock EXIT INT TERM

# Fast but recognizable freshweb preview preset.
# Goal: webcam shot in -> short AI motion clip out, while preserving enough
# facial and room detail to keep the result readable.

export FRESHWEB_FOLDER=${FRESHWEB_FOLDER:-freshweb-live-preview}
export FRESHWEB_POLLING_TIME_MS=${FRESHWEB_POLLING_TIME_MS:-1000}
export FRESHWEB_RETRY_ON_FAILURE=${FRESHWEB_RETRY_ON_FAILURE:-0}
export FRESHWEB_ENABLE_PAID_FAL_FALLBACKS=${FRESHWEB_ENABLE_PAID_FAL_FALLBACKS:-0}
export FRESHWEB_ALLOW_PAID_FAL_POLLING=${FRESHWEB_ALLOW_PAID_FAL_POLLING:-1}
export FRESHWEB_ALLOW_PAID_FAL_MULTI_SCENE=${FRESHWEB_ALLOW_PAID_FAL_MULTI_SCENE:-0}
export VIDEO_MODE_PRESET=${VIDEO_MODE_PRESET:-singleImageOnly}

export FRESHWEB_SINGLE_VIDEO_MODEL_TYPE=${FRESHWEB_SINGLE_VIDEO_MODEL_TYPE:-wan}
export FRESHWEB_SINGLE_VIDEO_PROMPT_FLAVOR=${FRESHWEB_SINGLE_VIDEO_PROMPT_FLAVOR:-default}
export FRESHWEB_SELF_HOSTED_SINGLE=${FRESHWEB_SELF_HOSTED_SINGLE:-0}
export WAN22_SINGLE_SPACE=${WAN22_SINGLE_SPACE:-Wan-AI/Wan-2.2-5B}
export WAN22_SINGLE_SELF_HOSTED_SPACE=${WAN22_SINGLE_SELF_HOSTED_SPACE:-eggman-poff/wan-mixed}
export FRESHWEB_WAN_SINGLE_FALLBACK_SPACES=${FRESHWEB_WAN_SINGLE_FALLBACK_SPACES:-$WAN22_SINGLE_SELF_HOSTED_SPACE}
export FRESHWEB_WAN_SINGLE_USE_HF_PROVIDER_FALLBACK=${FRESHWEB_WAN_SINGLE_USE_HF_PROVIDER_FALLBACK:-1}
export FRESHWEB_WAN_SINGLE_HF_PROVIDER=${FRESHWEB_WAN_SINGLE_HF_PROVIDER:-fal-ai}
export FRESHWEB_WAN_SINGLE_HF_MODEL=${FRESHWEB_WAN_SINGLE_HF_MODEL:-Wan-AI/Wan2.2-I2V-A14B}
export FRESHWEB_ENABLE_RUNWARE_FALLBACKS=${FRESHWEB_ENABLE_RUNWARE_FALLBACKS:-0}

export FRESHWEB_USE_MULTIMODALART_FIRST_LAST=${FRESHWEB_USE_MULTIMODALART_FIRST_LAST:-0}
export FRESHWEB_ENABLE_DRIFT_CORRECTION=${FRESHWEB_ENABLE_DRIFT_CORRECTION:-0}
export FRESHWEB_DISABLE_TAIL_PAD=${FRESHWEB_DISABLE_TAIL_PAD:-1}
export FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE=${FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE:-0}
export FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED=${FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED:-0}
export FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL=${FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL:-0}
export FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME=${FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME:-0}
export FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME=${FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME:-0}
export FRESHWEB_TRIPPY_REANCHOR_INTERVAL=${FRESHWEB_TRIPPY_REANCHOR_INTERVAL:-0}

export FRESHWEB_SCENE_COUNT=${FRESHWEB_SCENE_COUNT:-}
export FRESHWEB_SCENE_COUNT_TAKT_COUNT=${FRESHWEB_SCENE_COUNT_TAKT_COUNT:-1}
export FRESHWEB_SCENE_COUNT_TAKT=${FRESHWEB_SCENE_COUNT_TAKT:-3}
export FRESHWEB_SCENE_COUNT_TAKT_ZAEHLER=${FRESHWEB_SCENE_COUNT_TAKT_ZAEHLER:-3}
export FRESHWEB_SCENE_COUNT_TAKT_NENNER=${FRESHWEB_SCENE_COUNT_TAKT_NENNER:-4}
export FRESHWEB_SCENE_COUNT_TAKT_TYPE=${FRESHWEB_SCENE_COUNT_TAKT_TYPE:-balanced}
export FRESHWEB_SCENE_COUNT_BIAS=${FRESHWEB_SCENE_COUNT_BIAS:-0}
export FRESHWEB_SCENE_LENGTH_MULTIPLIER=${FRESHWEB_SCENE_LENGTH_MULTIPLIER:-1}
export FRESHWEB_MIN_SCENE_DURATION_SECONDS=${FRESHWEB_MIN_SCENE_DURATION_SECONDS:-1.6}
export FRESHWEB_SCENE_PLAN_TEMPERATURE=${FRESHWEB_SCENE_PLAN_TEMPERATURE:-0.25}
export FRESHWEB_SCENE_PLAN_TOP_P=${FRESHWEB_SCENE_PLAN_TOP_P:-0.85}

export FRESHWEB_IMAGE_WIDTH=${FRESHWEB_IMAGE_WIDTH:-448}
export FRESHWEB_IMAGE_HEIGHT=${FRESHWEB_IMAGE_HEIGHT:-336}
export FRESHWEB_VIDEO_WIDTH=${FRESHWEB_VIDEO_WIDTH:-448}
export FRESHWEB_VIDEO_HEIGHT=${FRESHWEB_VIDEO_HEIGHT:-336}
export FRESHWEB_SINGLE_VIDEO_WIDTH=${FRESHWEB_SINGLE_VIDEO_WIDTH:-448}
export FRESHWEB_SINGLE_VIDEO_HEIGHT=${FRESHWEB_SINGLE_VIDEO_HEIGHT:-336}
export FRESHWEB_VIDEO_CUSTOM_MAX_AREA=${FRESHWEB_VIDEO_CUSTOM_MAX_AREA:-150528}

export FRESHWEB_IMAGE_STEPS=${FRESHWEB_IMAGE_STEPS:-14}
export FRESHWEB_IMAGE_GUIDANCE=${FRESHWEB_IMAGE_GUIDANCE:-2.8}
export FRESHWEB_VIDEO_STEPS=${FRESHWEB_VIDEO_STEPS:-18}
export FRESHWEB_VIDEO_GUIDANCE=${FRESHWEB_VIDEO_GUIDANCE:-4.5}
export FRESHWEB_VIDEO_FPS=${FRESHWEB_VIDEO_FPS:-14}
export FRESHWEB_VIDEO_NUM_FRAMES=${FRESHWEB_VIDEO_NUM_FRAMES:-29}
export FRESHWEB_VIDEO_RANDOMIZE_SEED=${FRESHWEB_VIDEO_RANDOMIZE_SEED:-true}
export FRESHWEB_SINGLE_FPS=${FRESHWEB_SINGLE_FPS:-14}
export FRESHWEB_SINGLE_VIDEO_MAX_DURATION=${FRESHWEB_SINGLE_VIDEO_MAX_DURATION:-2}
export FRESHWEB_VIDEO_SAMPLING_STEPS=${FRESHWEB_VIDEO_SAMPLING_STEPS:-16}
export FRESHWEB_VIDEO_GUIDE_SCALE=${FRESHWEB_VIDEO_GUIDE_SCALE:-4.2}
export FRESHWEB_VIDEO_SHIFT=${FRESHWEB_VIDEO_SHIFT:-3}

sh "$(pwd)/MIX-again-freshweb.middle-cost-4-3.sh" "$@"
