#!/bin/zsh
set -euo pipefail

cd "$(dirname "$0")"

# Fast 4:3 preset for prompt tuning.
# Goal: cheap, quick runs that still show whether scene planning, wordstream,
# and camera prompts are working. Single iteration by default.
#
# Override any value at runtime, for example:
# FRESHWEB_WORDS='gallery,en | audience,en' sh lib/generator/adapter/MIX-again-freshweb.prompt-fast-4-3.sh

export FRESHWEB_FOLDER=${FRESHWEB_FOLDER:-freshweb-prompt-fast-4-3-test}
export FRESHWEB_POLLING_TIME_MS=${FRESHWEB_POLLING_TIME_MS:-0}
export VIDEO_MODE_PRESET=${VIDEO_MODE_PRESET:-storyDrivenMixed}

# Keep the prompt path readable and comparable across runs.
export FRESHWEB_USE_MULTIMODALART_FIRST_LAST=${FRESHWEB_USE_MULTIMODALART_FIRST_LAST:-1}
export FRESHWEB_ENABLE_DRIFT_CORRECTION=${FRESHWEB_ENABLE_DRIFT_CORRECTION:-0}
export FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE=${FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE:-0}
export FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED=${FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED:-0}
export FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME=${FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME:-0}
export FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME=${FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME:-0}

# Keep scenes readable, but short enough for quick iteration.
export FRESHWEB_SCENE_COUNT_TAKT=${FRESHWEB_SCENE_COUNT_TAKT:-3}
export FRESHWEB_SCENE_COUNT_TAKT_TYPE=${FRESHWEB_SCENE_COUNT_TAKT_TYPE:-balanced}
export FRESHWEB_SCENE_LENGTH_TAKT=${FRESHWEB_SCENE_LENGTH_TAKT:-3}
export FRESHWEB_SCENE_LENGTH_TAKT_TYPE=${FRESHWEB_SCENE_LENGTH_TAKT_TYPE:-balanced}
export FRESHWEB_SCENE_LENGTH_MULTIPLIER=${FRESHWEB_SCENE_LENGTH_MULTIPLIER:-1.15}
export FRESHWEB_MIN_SCENE_DURATION_SECONDS=${FRESHWEB_MIN_SCENE_DURATION_SECONDS:-1.6}
export FRESHWEB_SCENE_PLAN_TEMPERATURE=${FRESHWEB_SCENE_PLAN_TEMPERATURE:-0.25}
export FRESHWEB_SCENE_PLAN_TOP_P=${FRESHWEB_SCENE_PLAN_TOP_P:-0.78}

# Small 4:3 sizes that are still useful for face, room, and motion evaluation.
export FRESHWEB_IMAGE_WIDTH=${FRESHWEB_IMAGE_WIDTH:-384}
export FRESHWEB_IMAGE_HEIGHT=${FRESHWEB_IMAGE_HEIGHT:-288}
export FRESHWEB_VIDEO_WIDTH=${FRESHWEB_VIDEO_WIDTH:-384}
export FRESHWEB_VIDEO_HEIGHT=${FRESHWEB_VIDEO_HEIGHT:-288}
export FRESHWEB_SINGLE_VIDEO_WIDTH=${FRESHWEB_SINGLE_VIDEO_WIDTH:-384}
export FRESHWEB_SINGLE_VIDEO_HEIGHT=${FRESHWEB_SINGLE_VIDEO_HEIGHT:-288}
export FRESHWEB_VIDEO_CUSTOM_MAX_AREA=${FRESHWEB_VIDEO_CUSTOM_MAX_AREA:-110592}

# Faster render settings, but not so low that prompt differences disappear.
export FRESHWEB_IMAGE_STEPS=${FRESHWEB_IMAGE_STEPS:-12}
export FRESHWEB_IMAGE_GUIDANCE=${FRESHWEB_IMAGE_GUIDANCE:-2.5}
export FRESHWEB_VIDEO_STEPS=${FRESHWEB_VIDEO_STEPS:-16}
export FRESHWEB_VIDEO_GUIDANCE=${FRESHWEB_VIDEO_GUIDANCE:-4}
export FRESHWEB_VIDEO_FPS=${FRESHWEB_VIDEO_FPS:-12}
export FRESHWEB_VIDEO_NUM_FRAMES=${FRESHWEB_VIDEO_NUM_FRAMES:-41}
export FRESHWEB_VIDEO_RANDOMIZE_SEED=${FRESHWEB_VIDEO_RANDOMIZE_SEED:-true}
export FRESHWEB_SINGLE_FPS=${FRESHWEB_SINGLE_FPS:-16}
export FRESHWEB_SINGLE_VIDEO_MAX_DURATION=${FRESHWEB_SINGLE_VIDEO_MAX_DURATION:-3.2}
export FRESHWEB_VIDEO_SAMPLING_STEPS=${FRESHWEB_VIDEO_SAMPLING_STEPS:-16}
export FRESHWEB_VIDEO_GUIDE_SCALE=${FRESHWEB_VIDEO_GUIDE_SCALE:-4}
export FRESHWEB_VIDEO_SHIFT=${FRESHWEB_VIDEO_SHIFT:-3}

exec sh "$(pwd)/MIX-again-freshweb.middle-cost-4-3.sh" "$@"
