#!/bin/zsh
set -euo pipefail

cd "$(dirname "$0")"

# Human-readable preset for the freshweb 4:3 middle-cost camera pipeline.
# Override any value at runtime, for example:
# FRESHWEB_POLLING_TIME_MS=5000 sh lib/generator/adapter/MIX-again-freshweb.middle-cost-4-3.sh
# Set FRESHWEB_POLLING_TIME_MS=0 to run a single iteration.

# Story source
FRESHWEB_MODE=${FRESHWEB_MODE:-camera}
FRESHWEB_WORDS=${FRESHWEB_WORDS:-horror,en | fries,en }
FRESHWEB_FOLDER=${FRESHWEB_FOLDER:-freshweb-middle-cost-4-3-test}
FRESHWEB_POLLING_TIME_MS=${FRESHWEB_POLLING_TIME_MS:-5000}

# Compatibility fallback for generic webcam/person runs. The active planned
# Kaufhaus preset supplies its own location and protagonist-safe values.
FRESHWEB_OPENING_PROMPT=${FRESHWEB_OPENING_PROMPT:-freshweb webcam shot, candid documentary still, natural light, clear subject focus}
FRESHWEB_SCENE_VISUAL_DIRECTION=${FRESHWEB_SCENE_VISUAL_DIRECTION:-documentary, realistic, visually distinct scenes, coherent camera-led progression, better image quality, visible body motion, clear gesture changes, expressive face movement, readable camera movement}
FRESHWEB_USE_VISION=${FRESHWEB_USE_VISION:-1}
FRESHWEB_LOCK_PROMPT_CONTINUITY_TO_OPENING_FRAME=${FRESHWEB_LOCK_PROMPT_CONTINUITY_TO_OPENING_FRAME:-1}

# Restart behavior
# Reuse the previous movie's last extracted frame when the output folder is reused.
FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME=${FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME:-1}

# Mirelo audio toggle
# 1 = keep Mirelo audio on
# 0 = disable Mirelo entirely
FRESHWEB_MIRELO_AUDIO_ENABLED=${FRESHWEB_MIRELO_AUDIO_ENABLED:-1}
if [ "${FRESHWEB_MIRELO_AUDIO_ENABLED}" = "0" ]; then
  export FRESHWEB_MIRELO_MODE=off
  export FRESHWEB_MIRELO_RUNWARE_FALLBACK_ENABLED=0
else
  # finalOnly:
  #   generate one Mirelo audio track for the final concatenated movie
  # afterEachVideo:
  #   generate and mux Mirelo audio after every scene clip, then concat those clips
  export FRESHWEB_MIRELO_MODE=${FRESHWEB_MIRELO_MODE:-finalOnly}
  export FRESHWEB_MIRELO_RUNWARE_FALLBACK_ENABLED=${FRESHWEB_MIRELO_RUNWARE_FALLBACK_ENABLED:-1}
fi

# Rhythm and scene planning
FRESHWEB_USE_TAKTMUSTER_LENGTHS=${FRESHWEB_USE_TAKTMUSTER_LENGTHS:-1}
# Separate taktmuster controls:
# - scene count: how many scenes the sequence tends to get
# - scene length: the rhythm used for the per-scene duration pattern
FRESHWEB_SCENE_COUNT_TAKT=${FRESHWEB_SCENE_COUNT_TAKT:-4}
FRESHWEB_SCENE_COUNT_TAKT_TYPE=${FRESHWEB_SCENE_COUNT_TAKT_TYPE:-balanced}
FRESHWEB_SCENE_LENGTH_TAKT=${FRESHWEB_SCENE_LENGTH_TAKT:-3}
FRESHWEB_SCENE_LENGTH_TAKT_TYPE=${FRESHWEB_SCENE_LENGTH_TAKT_TYPE:-balanced}
FRESHWEB_SCENE_LENGTH_CURVE=${FRESHWEB_SCENE_LENGTH_CURVE:-linear}
FRESHWEB_SCENE_LENGTH_CURVE_EXPONENT=${FRESHWEB_SCENE_LENGTH_CURVE_EXPONENT:-1}
FRESHWEB_SCENE_LENGTH_PRESERVE_TOTAL=${FRESHWEB_SCENE_LENGTH_PRESERVE_TOTAL:-1}
FRESHWEB_SCENE_LENGTH_MAX_SECONDS=${FRESHWEB_SCENE_LENGTH_MAX_SECONDS:-}
# Legacy aliases remain supported in code, but the preset prefers the explicit names above.
FRESHWEB_SCENE_LENGTH_MULTIPLIER=${FRESHWEB_SCENE_LENGTH_MULTIPLIER:-1.6}
FRESHWEB_SCENE_LENGTH_BIAS=${FRESHWEB_SCENE_LENGTH_BIAS:-0}
FRESHWEB_SCENE_PLAN_TEMPERATURE=${FRESHWEB_SCENE_PLAN_TEMPERATURE:-0.35}
FRESHWEB_SCENE_PLAN_TOP_P=${FRESHWEB_SCENE_PLAN_TOP_P:-0.85}
# Keep short beats readable enough for visible webcam motion.
FRESHWEB_MIN_SCENE_DURATION_SECONDS=${FRESHWEB_MIN_SCENE_DURATION_SECONDS:-1.6}

# Video mode preset
# singleImageOnly:
#   all clips use image-to-video only, no first/last-frame model
# storyDrivenMixed:
#   scene planning may choose between singleImage and firstLast
VIDEO_MODE_PRESET=${VIDEO_MODE_PRESET:-storyDrivenMixed}

case "$VIDEO_MODE_PRESET" in
  singleImageOnly)
    FRESHWEB_IMAGE_TO_VIDEO_ONLY=${FRESHWEB_IMAGE_TO_VIDEO_ONLY:-1}
    FRESHWEB_FIRST_CLIP_VIDEO_MODE=${FRESHWEB_FIRST_CLIP_VIDEO_MODE:-singleImage}
    FRESHWEB_LATER_CLIPS_SINGLE_IMAGE=${FRESHWEB_LATER_CLIPS_SINGLE_IMAGE:-1}
    FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS=${FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS:-0}
    FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE=${FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE:-0}
    ;;
  storyDrivenMixed)
    FRESHWEB_IMAGE_TO_VIDEO_ONLY=${FRESHWEB_IMAGE_TO_VIDEO_ONLY:-0}
    FRESHWEB_FIRST_CLIP_VIDEO_MODE=${FRESHWEB_FIRST_CLIP_VIDEO_MODE:-singleImage}
    FRESHWEB_LATER_CLIPS_SINGLE_IMAGE=${FRESHWEB_LATER_CLIPS_SINGLE_IMAGE:-0}
    FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS=${FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS:-1}
    FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE=${FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE:-1}
    ;;
  *)
    echo "Unknown VIDEO_MODE_PRESET: $VIDEO_MODE_PRESET" >&2
    echo "Expected: singleImageOnly or storyDrivenMixed" >&2
    exit 1
    ;;
esac

# Still-image generation
# Explicit 4:3 defaults with a lighter baseline than the previous 512x384
# profile. This keeps the format stable while bringing iteration speed back up.
FRESHWEB_VIDEO_ASPECT_RATIO=${FRESHWEB_VIDEO_ASPECT_RATIO:-4:3}
FRESHWEB_IMAGE_WIDTH=${FRESHWEB_IMAGE_WIDTH:-448}
FRESHWEB_IMAGE_HEIGHT=${FRESHWEB_IMAGE_HEIGHT:-336}
FRESHWEB_IMAGE_STEPS=${FRESHWEB_IMAGE_STEPS:-14}
FRESHWEB_IMAGE_GUIDANCE=${FRESHWEB_IMAGE_GUIDANCE:-2.8}
# Opening-start FLUX-Kontext should stay on the same 4:3 canvas and avoid
# paying for a larger hidden default.
FRESHWEB_OPENING_START_WIDTH=${FRESHWEB_OPENING_START_WIDTH:-$FRESHWEB_IMAGE_WIDTH}
FRESHWEB_OPENING_START_HEIGHT=${FRESHWEB_OPENING_START_HEIGHT:-$FRESHWEB_IMAGE_HEIGHT}
FRESHWEB_OPENING_START_STEPS=${FRESHWEB_OPENING_START_STEPS:-18}
FRESHWEB_OPENING_START_GUIDANCE=${FRESHWEB_OPENING_START_GUIDANCE:-2.8}
# Optional FLUX Kontext drift-correction step between chained scene clips.
# This edits the last video frame into a cleaner continuity still before the
# next scene starts. Keep it off by default because it adds another paid call.
FRESHWEB_ENABLE_DRIFT_CORRECTION=${FRESHWEB_ENABLE_DRIFT_CORRECTION:-0}
FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE=${FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE:-0}
FRESHWEB_DRIFT_CORRECTION_MODEL=${FRESHWEB_DRIFT_CORRECTION_MODEL:-black-forest-labs/FLUX.1-Kontext-dev}
FRESHWEB_DRIFT_CORRECTION_PROVIDER=${FRESHWEB_DRIFT_CORRECTION_PROVIDER:-fal-ai}
FRESHWEB_DRIFT_CORRECTION_STEPS=${FRESHWEB_DRIFT_CORRECTION_STEPS:-20}
FRESHWEB_DRIFT_CORRECTION_GUIDANCE=${FRESHWEB_DRIFT_CORRECTION_GUIDANCE:-3.1}
FRESHWEB_DRIFT_CORRECTION_NEGATIVE_PROMPT=${FRESHWEB_DRIFT_CORRECTION_NEGATIVE_PROMPT:-different subject, different location, changed identity, new props, distorted anatomy, blur, low detail}
FRESHWEB_DRIFT_CORRECTION_SEED=${FRESHWEB_DRIFT_CORRECTION_SEED:-0}
FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED=${FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED:-1}
FRESHWEB_DRIFT_CONTEXT_BUFFER_SIZE=${FRESHWEB_DRIFT_CONTEXT_BUFFER_SIZE:-8}
FRESHWEB_DRIFT_CONTEXT_BUFFER_COLUMNS=${FRESHWEB_DRIFT_CONTEXT_BUFFER_COLUMNS:-4}
FRESHWEB_DRIFT_CONTEXT_BUFFER_ROWS=${FRESHWEB_DRIFT_CONTEXT_BUFFER_ROWS:-2}
FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL=${FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL:-1}

# First/last video settings
# Kept for compatibility, but unused while FRESHWEB_IMAGE_TO_VIDEO_ONLY=1.
FRESHWEB_VIDEO_WIDTH=${FRESHWEB_VIDEO_WIDTH:-448}
FRESHWEB_VIDEO_HEIGHT=${FRESHWEB_VIDEO_HEIGHT:-336}
FRESHWEB_VIDEO_STEPS=${FRESHWEB_VIDEO_STEPS:-18}
FRESHWEB_VIDEO_GUIDANCE=${FRESHWEB_VIDEO_GUIDANCE:-4.5}
FRESHWEB_VIDEO_FPS=${FRESHWEB_VIDEO_FPS:-10}
FRESHWEB_VIDEO_NUM_FRAMES=${FRESHWEB_VIDEO_NUM_FRAMES:-41}
FRESHWEB_VIDEO_CUSTOM_MAX_AREA=${FRESHWEB_VIDEO_CUSTOM_MAX_AREA:-150528}
FRESHWEB_VIDEO_RANDOMIZE_SEED=${FRESHWEB_VIDEO_RANDOMIZE_SEED:-1}

# Image-to-video settings
FRESHWEB_SINGLE_VIDEO_WIDTH=${FRESHWEB_SINGLE_VIDEO_WIDTH:-448}
FRESHWEB_SINGLE_VIDEO_HEIGHT=${FRESHWEB_SINGLE_VIDEO_HEIGHT:-336}
FRESHWEB_SINGLE_FPS=${FRESHWEB_SINGLE_FPS:-14}
FRESHWEB_VIDEO_SAMPLING_STEPS=${FRESHWEB_VIDEO_SAMPLING_STEPS:-16}
FRESHWEB_VIDEO_GUIDE_SCALE=${FRESHWEB_VIDEO_GUIDE_SCALE:-4.2}
FRESHWEB_VIDEO_SHIFT=${FRESHWEB_VIDEO_SHIFT:-3}
FRESHWEB_DRIFT_CORRECTION_WIDTH=${FRESHWEB_DRIFT_CORRECTION_WIDTH:-$FRESHWEB_SINGLE_VIDEO_WIDTH}
FRESHWEB_DRIFT_CORRECTION_HEIGHT=${FRESHWEB_DRIFT_CORRECTION_HEIGHT:-$FRESHWEB_SINGLE_VIDEO_HEIGHT}

# Audio
FRESHWEB_MIRELO_STEPS=${FRESHWEB_MIRELO_STEPS:-10}
FRESHWEB_MIRELO_CREATIVITY=${FRESHWEB_MIRELO_CREATIVITY:-2.8}

# Self-hosted WAN routing
WAN22_SINGLE_SELF_HOSTED_SPACE=${WAN22_SINGLE_SELF_HOSTED_SPACE:-eggman-poff/wan-mixed}
WAN22_FIRST_LAST_SELF_HOSTED_SPACE=${WAN22_FIRST_LAST_SELF_HOSTED_SPACE:-eggman-poff/wan-mixed}

# Camera
FRESHWEB_CAMERA_OUTPUT_DIR=${FRESHWEB_CAMERA_OUTPUT_DIR:-$(pwd)/../../../tests/GENERATIONS/camera-shot}
FRESHWEB_VALIDATE_CAMERA_SHOT=${FRESHWEB_VALIDATE_CAMERA_SHOT:-0}

export \
  VIDEO_MODE_PRESET \
  FRESHWEB_MODE \
  FRESHWEB_WORDS \
  FRESHWEB_FOLDER \
  FRESHWEB_POLLING_TIME_MS \
  FRESHWEB_OPENING_PROMPT \
  FRESHWEB_SCENE_VISUAL_DIRECTION \
  FRESHWEB_USE_VISION \
  FRESHWEB_LOCK_PROMPT_CONTINUITY_TO_OPENING_FRAME \
  FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME \
  FRESHWEB_MIRELO_AUDIO_ENABLED \
  FRESHWEB_MIRELO_MODE \
  FRESHWEB_MIRELO_RUNWARE_FALLBACK_ENABLED \
  FRESHWEB_USE_TAKTMUSTER_LENGTHS \
  FRESHWEB_SCENE_COUNT_TAKT \
  FRESHWEB_SCENE_COUNT_TAKT_TYPE \
  FRESHWEB_SCENE_LENGTH_TAKT \
  FRESHWEB_SCENE_LENGTH_TAKT_TYPE \
  FRESHWEB_SCENE_LENGTH_CURVE \
  FRESHWEB_SCENE_LENGTH_CURVE_EXPONENT \
  FRESHWEB_SCENE_LENGTH_PRESERVE_TOTAL \
  FRESHWEB_SCENE_LENGTH_MAX_SECONDS \
  FRESHWEB_SCENE_LENGTH_MULTIPLIER \
  FRESHWEB_SCENE_LENGTH_BIAS \
  FRESHWEB_SCENE_PLAN_TEMPERATURE \
  FRESHWEB_SCENE_PLAN_TOP_P \
  FRESHWEB_MIN_SCENE_DURATION_SECONDS \
  FRESHWEB_CAMERA_SINGLE_IMAGE_STABILITY_MAX_DURATION \
  FRESHWEB_IMAGE_TO_VIDEO_ONLY \
  FRESHWEB_FIRST_CLIP_VIDEO_MODE \
  FRESHWEB_LATER_CLIPS_SINGLE_IMAGE \
  FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS \
  FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE \
  FRESHWEB_IMAGE_WIDTH \
  FRESHWEB_IMAGE_HEIGHT \
  FRESHWEB_IMAGE_STEPS \
  FRESHWEB_IMAGE_GUIDANCE \
  FRESHWEB_VIDEO_ASPECT_RATIO \
  FRESHWEB_OPENING_START_WIDTH \
  FRESHWEB_OPENING_START_HEIGHT \
  FRESHWEB_OPENING_START_STEPS \
  FRESHWEB_OPENING_START_GUIDANCE \
  FRESHWEB_ENABLE_DRIFT_CORRECTION \
  FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE \
  FRESHWEB_LOCAL_LOCATION_DRIFT_CORRECTION_PERCENT \
  FRESHWEB_DRIFT_CORRECTION_MODEL \
  FRESHWEB_DRIFT_CORRECTION_PROVIDER \
  FRESHWEB_DRIFT_CORRECTION_STEPS \
  FRESHWEB_DRIFT_CORRECTION_GUIDANCE \
  FRESHWEB_DRIFT_CORRECTION_NEGATIVE_PROMPT \
  FRESHWEB_DRIFT_CORRECTION_SEED \
  FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED \
  FRESHWEB_DRIFT_CONTEXT_BUFFER_SIZE \
  FRESHWEB_DRIFT_CONTEXT_BUFFER_COLUMNS \
  FRESHWEB_DRIFT_CONTEXT_BUFFER_ROWS \
  FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL \
  FRESHWEB_DRIFT_CORRECTION_WIDTH \
  FRESHWEB_DRIFT_CORRECTION_HEIGHT \
  FRESHWEB_VIDEO_WIDTH \
  FRESHWEB_VIDEO_HEIGHT \
  FRESHWEB_VIDEO_STEPS \
  FRESHWEB_VIDEO_GUIDANCE \
  FRESHWEB_VIDEO_FPS \
  FRESHWEB_VIDEO_NUM_FRAMES \
  FRESHWEB_VIDEO_CUSTOM_MAX_AREA \
  FRESHWEB_VIDEO_RANDOMIZE_SEED \
  FRESHWEB_SINGLE_VIDEO_WIDTH \
  FRESHWEB_SINGLE_VIDEO_HEIGHT \
  FRESHWEB_SINGLE_FPS \
  FRESHWEB_VIDEO_SAMPLING_STEPS \
  FRESHWEB_VIDEO_GUIDE_SCALE \
  FRESHWEB_VIDEO_SHIFT \
  FRESHWEB_MIRELO_STEPS \
  FRESHWEB_MIRELO_CREATIVITY \
  WAN22_SINGLE_SELF_HOSTED_SPACE \
  WAN22_FIRST_LAST_SELF_HOSTED_SPACE \
  FRESHWEB_CAMERA_OUTPUT_DIR \
  FRESHWEB_VALIDATE_CAMERA_SHOT

node "$(pwd)/MIX-again-freshweb.js" "$@"
