#!/bin/zsh
set -euo pipefail

cd "$(dirname "$0")"

# WAN needs more render headroom than the tiny LTX fast preset to avoid muddy,
# unreadable output. Keep the same trippy prompt flavor and fallback order, but
# use a balanced 4:3 quality profile for clearer faces, motion, and texture.

export FRESHWEB_FOLDER=${FRESHWEB_FOLDER:-freshweb-prompt-fast-wan-trippy-4-3-test}
export FRESHWEB_POLLING_TIME_MS=${FRESHWEB_POLLING_TIME_MS:-1000}
export VIDEO_MODE_PRESET=${VIDEO_MODE_PRESET:-singleImageOnly}

export FRESHWEB_SINGLE_VIDEO_MODEL_TYPE=${FRESHWEB_SINGLE_VIDEO_MODEL_TYPE:-wan}
export FRESHWEB_SINGLE_VIDEO_PROMPT_FLAVOR=${FRESHWEB_SINGLE_VIDEO_PROMPT_FLAVOR:-ltxTrippy}
export FRESHWEB_SELF_HOSTED_SINGLE=${FRESHWEB_SELF_HOSTED_SINGLE:-0}
export WAN22_SINGLE_SPACE=${WAN22_SINGLE_SPACE:-Wan-AI/Wan-2.2-5B}
export WAN22_SINGLE_SELF_HOSTED_SPACE=${WAN22_SINGLE_SELF_HOSTED_SPACE:-eggman-poff/wan-mixed}
export FRESHWEB_WAN_SINGLE_FALLBACK_SPACES=${FRESHWEB_WAN_SINGLE_FALLBACK_SPACES:-$WAN22_SINGLE_SELF_HOSTED_SPACE}
export FRESHWEB_WAN_SINGLE_USE_HF_PROVIDER_FALLBACK=${FRESHWEB_WAN_SINGLE_USE_HF_PROVIDER_FALLBACK:-0}
export FRESHWEB_WAN_SINGLE_HF_PROVIDER=${FRESHWEB_WAN_SINGLE_HF_PROVIDER:-fal-ai}
export FRESHWEB_WAN_SINGLE_HF_MODEL=${FRESHWEB_WAN_SINGLE_HF_MODEL:-Wan-AI/Wan2.2-I2V-A14B}
export FRESHWEB_ENABLE_RUNWARE_FALLBACKS=${FRESHWEB_ENABLE_RUNWARE_FALLBACKS:-0}

export FRESHWEB_USE_MULTIMODALART_FIRST_LAST=${FRESHWEB_USE_MULTIMODALART_FIRST_LAST:-0}
export FRESHWEB_DRIFT_CORRECTION_LEVEL=${FRESHWEB_DRIFT_CORRECTION_LEVEL:-aggressive}
export FRESHWEB_ENABLE_DRIFT_CORRECTION=${FRESHWEB_ENABLE_DRIFT_CORRECTION:-1}
export FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE=${FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE:-1}
export FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED=${FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED:-0}
export FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL=${FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL:-0}
export FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME=${FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME:-0}
export FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME=${FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME:-1}
export FRESHWEB_TRIPPY_REANCHOR_INTERVAL=${FRESHWEB_TRIPPY_REANCHOR_INTERVAL:-0}

export FRESHWEB_SCENE_COUNT_TAKT_COUNT=${FRESHWEB_SCENE_COUNT_TAKT_COUNT:-2}
export FRESHWEB_SCENE_COUNT_TAKT_ZAEHLER=${FRESHWEB_SCENE_COUNT_TAKT_ZAEHLER:-3}
export FRESHWEB_SCENE_COUNT_TAKT_NENNER=${FRESHWEB_SCENE_COUNT_TAKT_NENNER:-4}
export FRESHWEB_SCENE_COUNT_TAKT_TYPE=${FRESHWEB_SCENE_COUNT_TAKT_TYPE:-balanced}
export FRESHWEB_SCENE_COUNT_BIAS=${FRESHWEB_SCENE_COUNT_BIAS:-4}
export FRESHWEB_SCENE_LENGTH_TAKT=${FRESHWEB_SCENE_LENGTH_TAKT:-3}
export FRESHWEB_SCENE_LENGTH_TAKT_TYPE=${FRESHWEB_SCENE_LENGTH_TAKT_TYPE:-balanced}
export FRESHWEB_SCENE_LENGTH_MULTIPLIER=${FRESHWEB_SCENE_LENGTH_MULTIPLIER:-1.9}
export FRESHWEB_MIN_SCENE_DURATION_SECONDS=${FRESHWEB_MIN_SCENE_DURATION_SECONDS:-2.4}
export FRESHWEB_SCENE_PLAN_TEMPERATURE=${FRESHWEB_SCENE_PLAN_TEMPERATURE:-0.5}
export FRESHWEB_SCENE_PLAN_TOP_P=${FRESHWEB_SCENE_PLAN_TOP_P:-0.92}

export FRESHWEB_IMAGE_WIDTH=${FRESHWEB_IMAGE_WIDTH:-448}
export FRESHWEB_IMAGE_HEIGHT=${FRESHWEB_IMAGE_HEIGHT:-336}
export FRESHWEB_VIDEO_WIDTH=${FRESHWEB_VIDEO_WIDTH:-448}
export FRESHWEB_VIDEO_HEIGHT=${FRESHWEB_VIDEO_HEIGHT:-336}
export FRESHWEB_SINGLE_VIDEO_WIDTH=${FRESHWEB_SINGLE_VIDEO_WIDTH:-448}
export FRESHWEB_SINGLE_VIDEO_HEIGHT=${FRESHWEB_SINGLE_VIDEO_HEIGHT:-336}
export FRESHWEB_VIDEO_CUSTOM_MAX_AREA=${FRESHWEB_VIDEO_CUSTOM_MAX_AREA:-150528}

export FRESHWEB_IMAGE_STEPS=${FRESHWEB_IMAGE_STEPS:-16}
export FRESHWEB_IMAGE_GUIDANCE=${FRESHWEB_IMAGE_GUIDANCE:-3}
export FRESHWEB_VIDEO_STEPS=${FRESHWEB_VIDEO_STEPS:-24}
export FRESHWEB_VIDEO_GUIDANCE=${FRESHWEB_VIDEO_GUIDANCE:-5}
export FRESHWEB_VIDEO_FPS=${FRESHWEB_VIDEO_FPS:-16}
export FRESHWEB_VIDEO_NUM_FRAMES=${FRESHWEB_VIDEO_NUM_FRAMES:-49}
export FRESHWEB_VIDEO_RANDOMIZE_SEED=${FRESHWEB_VIDEO_RANDOMIZE_SEED:-true}
export FRESHWEB_SINGLE_FPS=${FRESHWEB_SINGLE_FPS:-20}
export FRESHWEB_SINGLE_VIDEO_MAX_DURATION=${FRESHWEB_SINGLE_VIDEO_MAX_DURATION:-4.8}
export FRESHWEB_VIDEO_SAMPLING_STEPS=${FRESHWEB_VIDEO_SAMPLING_STEPS:-24}
export FRESHWEB_VIDEO_GUIDE_SCALE=${FRESHWEB_VIDEO_GUIDE_SCALE:-5}
export FRESHWEB_VIDEO_SHIFT=${FRESHWEB_VIDEO_SHIFT:-4}

exec sh "$(pwd)/MIX-again-freshweb.middle-cost-4-3.sh" "$@"
