#!/bin/zsh
set -euo pipefail

cd "$(dirname "$0")"

# Hugging Face Space test preset.
# Goal: use multimodalart/wan2-1-fast directly as the WAN alternative, with a
# small canvas and no fal/runware/self-hosted fallback chain.

export FRESHWEB_FOLDER=${FRESHWEB_FOLDER:-freshweb-hf-space-wan2-fast-test}
export FRESHWEB_POLLING_TIME_MS=${FRESHWEB_POLLING_TIME_MS:-0}
export FRESHWEB_ALLOW_PAID_FAL_POLLING=${FRESHWEB_ALLOW_PAID_FAL_POLLING:-0}
export FRESHWEB_ALLOW_PAID_FAL_MULTI_SCENE=${FRESHWEB_ALLOW_PAID_FAL_MULTI_SCENE:-0}
export FRESHWEB_ENABLE_PAID_FAL_FALLBACKS=${FRESHWEB_ENABLE_PAID_FAL_FALLBACKS:-0}
export FRESHWEB_ENABLE_RUNWARE_FALLBACKS=${FRESHWEB_ENABLE_RUNWARE_FALLBACKS:-0}

export VIDEO_MODE_PRESET=${VIDEO_MODE_PRESET:-singleImageOnly}
export FRESHWEB_MODE=${FRESHWEB_MODE:-reference-image-actor}
export FRESHWEB_USE_VISION=${FRESHWEB_USE_VISION:-0}
export FRESHWEB_VALIDATE_CAMERA_SHOT=${FRESHWEB_VALIDATE_CAMERA_SHOT:-0}
export FRESHWEB_PROTAGONIST_IMAGE_URL=${FRESHWEB_PROTAGONIST_IMAGE_URL:-https://dailydoase.de/v/315-HF-/1-62601.png}
export FRESHWEB_CAMERA_IMAGE_URL=${FRESHWEB_CAMERA_IMAGE_URL:-$FRESHWEB_PROTAGONIST_IMAGE_URL}

export FRESHWEB_SINGLE_VIDEO_MODEL_TYPE=${FRESHWEB_SINGLE_VIDEO_MODEL_TYPE:-wan}
export FRESHWEB_SINGLE_VIDEO_PROMPT_FLAVOR=${FRESHWEB_SINGLE_VIDEO_PROMPT_FLAVOR:-default}
export FRESHWEB_SELF_HOSTED_SINGLE=${FRESHWEB_SELF_HOSTED_SINGLE:-0}
export WAN22_SINGLE_SPACE=${WAN22_SINGLE_SPACE:-multimodalart/wan2-1-fast}
export FRESHWEB_WAN_SINGLE_FORCE_HF_PROVIDER=${FRESHWEB_WAN_SINGLE_FORCE_HF_PROVIDER:-0}
export FRESHWEB_WAN_SINGLE_USE_HF_PROVIDER_FALLBACK=${FRESHWEB_WAN_SINGLE_USE_HF_PROVIDER_FALLBACK:-0}
export FRESHWEB_WAN_SINGLE_FALLBACK_SPACES=${FRESHWEB_WAN_SINGLE_FALLBACK_SPACES:-}

export FRESHWEB_USE_MULTIMODALART_FIRST_LAST=${FRESHWEB_USE_MULTIMODALART_FIRST_LAST:-0}
export FRESHWEB_ENABLE_DRIFT_CORRECTION=${FRESHWEB_ENABLE_DRIFT_CORRECTION:-0}
export FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE=${FRESHWEB_DRIFT_CORRECTION_USE_CAMERA_REFERENCE:-0}
export FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED=${FRESHWEB_DRIFT_CONTEXT_BUFFER_ENABLED:-0}
export FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL=${FRESHWEB_DRIFT_CONTEXT_BUFFER_CAPTURE_BEFORE_EACH_CALL:-0}
export FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME=${FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME:-0}
export FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME=${FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME:-0}
export FRESHWEB_TRIPPY_REANCHOR_INTERVAL=${FRESHWEB_TRIPPY_REANCHOR_INTERVAL:-0}

export FRESHWEB_SCENE_COUNT=${FRESHWEB_SCENE_COUNT:-1}
export FRESHWEB_SCENE_COUNT_TAKT_COUNT=${FRESHWEB_SCENE_COUNT_TAKT_COUNT:-1}
export FRESHWEB_SCENE_COUNT_TAKT_ZAEHLER=${FRESHWEB_SCENE_COUNT_TAKT_ZAEHLER:-1}
export FRESHWEB_SCENE_COUNT_TAKT_NENNER=${FRESHWEB_SCENE_COUNT_TAKT_NENNER:-1}
export FRESHWEB_SCENE_COUNT_TAKT_TYPE=${FRESHWEB_SCENE_COUNT_TAKT_TYPE:-balanced}
export FRESHWEB_SCENE_COUNT_BIAS=${FRESHWEB_SCENE_COUNT_BIAS:-0}
export FRESHWEB_SCENE_LENGTH_TAKT=${FRESHWEB_SCENE_LENGTH_TAKT:-2}
export FRESHWEB_SCENE_LENGTH_TAKT_TYPE=${FRESHWEB_SCENE_LENGTH_TAKT_TYPE:-balanced}
export FRESHWEB_SCENE_LENGTH_MULTIPLIER=${FRESHWEB_SCENE_LENGTH_MULTIPLIER:-1}
export FRESHWEB_SCENE_LENGTH_BIAS=${FRESHWEB_SCENE_LENGTH_BIAS:-0}
export FRESHWEB_MIN_SCENE_DURATION_SECONDS=${FRESHWEB_MIN_SCENE_DURATION_SECONDS:-1.6}
export FRESHWEB_SCENE_PLAN_TEMPERATURE=${FRESHWEB_SCENE_PLAN_TEMPERATURE:-0.2}
export FRESHWEB_SCENE_PLAN_TOP_P=${FRESHWEB_SCENE_PLAN_TOP_P:-0.8}

export FRESHWEB_IMAGE_WIDTH=${FRESHWEB_IMAGE_WIDTH:-256}
export FRESHWEB_IMAGE_HEIGHT=${FRESHWEB_IMAGE_HEIGHT:-192}
export FRESHWEB_VIDEO_WIDTH=${FRESHWEB_VIDEO_WIDTH:-256}
export FRESHWEB_VIDEO_HEIGHT=${FRESHWEB_VIDEO_HEIGHT:-192}
export FRESHWEB_SINGLE_VIDEO_WIDTH=${FRESHWEB_SINGLE_VIDEO_WIDTH:-256}
export FRESHWEB_SINGLE_VIDEO_HEIGHT=${FRESHWEB_SINGLE_VIDEO_HEIGHT:-192}
export FRESHWEB_VIDEO_CUSTOM_MAX_AREA=${FRESHWEB_VIDEO_CUSTOM_MAX_AREA:-49152}
export FRESHWEB_DRIFT_CORRECTION_WIDTH=${FRESHWEB_DRIFT_CORRECTION_WIDTH:-256}
export FRESHWEB_DRIFT_CORRECTION_HEIGHT=${FRESHWEB_DRIFT_CORRECTION_HEIGHT:-192}

export FRESHWEB_IMAGE_STEPS=${FRESHWEB_IMAGE_STEPS:-8}
export FRESHWEB_IMAGE_GUIDANCE=${FRESHWEB_IMAGE_GUIDANCE:-2.2}
export FRESHWEB_VIDEO_STEPS=${FRESHWEB_VIDEO_STEPS:-12}
export FRESHWEB_VIDEO_GUIDANCE=${FRESHWEB_VIDEO_GUIDANCE:-3.5}
export FRESHWEB_VIDEO_FPS=${FRESHWEB_VIDEO_FPS:-12}
export FRESHWEB_VIDEO_NUM_FRAMES=${FRESHWEB_VIDEO_NUM_FRAMES:-33}
export FRESHWEB_VIDEO_RANDOMIZE_SEED=${FRESHWEB_VIDEO_RANDOMIZE_SEED:-1}
export FRESHWEB_SINGLE_FPS=${FRESHWEB_SINGLE_FPS:-12}
export FRESHWEB_SINGLE_VIDEO_MAX_DURATION=${FRESHWEB_SINGLE_VIDEO_MAX_DURATION:-2.4}
export FRESHWEB_VIDEO_SAMPLING_STEPS=${FRESHWEB_VIDEO_SAMPLING_STEPS:-12}
export FRESHWEB_VIDEO_GUIDE_SCALE=${FRESHWEB_VIDEO_GUIDE_SCALE:-3.5}
export FRESHWEB_VIDEO_SHIFT=${FRESHWEB_VIDEO_SHIFT:-3}

export FRESHWEB_MIRELO_MODE=${FRESHWEB_MIRELO_MODE:-afterEachVideo}
export FRESHWEB_MIRELO_STEPS=${FRESHWEB_MIRELO_STEPS:-6}
export FRESHWEB_MIRELO_CREATIVITY=${FRESHWEB_MIRELO_CREATIVITY:-1.4}

exec sh "$(pwd)/MIX-again-freshweb.middle-cost-4-3.sh" "$@"
