#!/bin/zsh
set -euo pipefail

cd "$(dirname "$0")"

# Balanced 4:3 preset: noticeably better than min-res, but still cheaper than
# the full middle-cost size. Override any value at runtime, for example:
# FRESHWEB_SINGLE_FPS=18 sh lib/generator/adapter/MIX-again-freshweb.balanced-good-quality-4-3.sh

export FRESHWEB_FOLDER="${FRESHWEB_FOLDER:-freshweb-balanced-good-quality-4-3-test}"
export FRESHWEB_POLLING_TIME_MS="${FRESHWEB_POLLING_TIME_MS:-1000}"
export FRESHWEB_SCENE_LENGTH_MULTIPLIER="${FRESHWEB_SCENE_LENGTH_MULTIPLIER:-1.2}"
export FRESHWEB_MIN_SCENE_DURATION_SECONDS="${FRESHWEB_MIN_SCENE_DURATION_SECONDS:-1.6}"
export FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME="${FRESHWEB_CHAIN_FROM_PREVIOUS_LOOP_LAST_FRAME:-0}"
export FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME="${FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME:-0}"
# Keep the cheaper balanced flow on one warm single-image model by default.
export VIDEO_MODE_PRESET="${VIDEO_MODE_PRESET:-singleImageOnly}"

# Cheaper than 512x384, but with enough headroom for more stable faces and
# smoother motion than the 320x240 min-res preset.
export FRESHWEB_IMAGE_WIDTH="${FRESHWEB_IMAGE_WIDTH:-448}"
export FRESHWEB_IMAGE_HEIGHT="${FRESHWEB_IMAGE_HEIGHT:-336}"
export FRESHWEB_VIDEO_WIDTH="${FRESHWEB_VIDEO_WIDTH:-448}"
export FRESHWEB_VIDEO_HEIGHT="${FRESHWEB_VIDEO_HEIGHT:-336}"
export FRESHWEB_SINGLE_VIDEO_WIDTH="${FRESHWEB_SINGLE_VIDEO_WIDTH:-448}"
export FRESHWEB_SINGLE_VIDEO_HEIGHT="${FRESHWEB_SINGLE_VIDEO_HEIGHT:-336}"
export FRESHWEB_VIDEO_CUSTOM_MAX_AREA="${FRESHWEB_VIDEO_CUSTOM_MAX_AREA:-150528}"

# Keep the stronger video defaults that have behaved best in the 4:3 wrappers.
export FRESHWEB_IMAGE_STEPS="${FRESHWEB_IMAGE_STEPS:-16}"
export FRESHWEB_IMAGE_GUIDANCE="${FRESHWEB_IMAGE_GUIDANCE:-3}"
export FRESHWEB_VIDEO_STEPS="${FRESHWEB_VIDEO_STEPS:-24}"
export FRESHWEB_VIDEO_GUIDANCE="${FRESHWEB_VIDEO_GUIDANCE:-5}"
export FRESHWEB_VIDEO_FPS="${FRESHWEB_VIDEO_FPS:-16}"
export FRESHWEB_VIDEO_NUM_FRAMES="${FRESHWEB_VIDEO_NUM_FRAMES:-49}"
export FRESHWEB_VIDEO_RANDOMIZE_SEED="${FRESHWEB_VIDEO_RANDOMIZE_SEED:-true}"
export FRESHWEB_SINGLE_FPS="${FRESHWEB_SINGLE_FPS:-20}"
export FRESHWEB_SINGLE_VIDEO_MAX_DURATION="${FRESHWEB_SINGLE_VIDEO_MAX_DURATION:-3.2}"
export FRESHWEB_VIDEO_SAMPLING_STEPS="${FRESHWEB_VIDEO_SAMPLING_STEPS:-24}"
export FRESHWEB_VIDEO_GUIDE_SCALE="${FRESHWEB_VIDEO_GUIDE_SCALE:-5}"
export FRESHWEB_VIDEO_SHIFT="${FRESHWEB_VIDEO_SHIFT:-4}"

exec sh "$(pwd)/MIX-again-freshweb.middle-cost-4-3.sh" "$@"
