#!/bin/zsh
set -euo pipefail

cd "$(dirname "$0")"

# Human-readable preset for the freshweb 4:3 middle-cost camera pipeline.
# Override any value at runtime, for example:
# FRESHWEB_POLLING_TIME_MS=5000 sh lib/generator/adapter/MIX-again-freshweb.middle-cost-4-3.sh

# Story source
FRESHWEB_MODE=${FRESHWEB_MODE:-camera}
FRESHWEB_WORDS=${FRESHWEB_WORDS:-horror,de}
FRESHWEB_FOLDER=${FRESHWEB_FOLDER:-freshweb-middle-cost-4-3-test}

# Opening frame and visual direction
FRESHWEB_OPENING_PROMPT=${FRESHWEB_OPENING_PROMPT:-freshweb webcam shot, candid documentary still, natural light, clear subject focus}
FRESHWEB_SCENE_VISUAL_DIRECTION=${FRESHWEB_SCENE_VISUAL_DIRECTION:-documentary, realistic, visually distinct scenes, coherent camera-led progression, better image quality, visible body motion, clear gesture changes, expressive face movement, readable camera movement}
FRESHWEB_USE_VISION=${FRESHWEB_USE_VISION:-1}
FRESHWEB_LOCK_PROMPT_CONTINUITY_TO_OPENING_FRAME=${FRESHWEB_LOCK_PROMPT_CONTINUITY_TO_OPENING_FRAME:-1}

# Restart behavior
# Reuse the previous movie's last extracted frame when the output folder is reused.
FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME=${FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME:-1}

# Rhythm and scene planning
FRESHWEB_USE_TAKTMUSTER_LENGTHS=${FRESHWEB_USE_TAKTMUSTER_LENGTHS:-1}
FRESHWEB_TAKT=${FRESHWEB_TAKT:-4}
FRESHWEB_TAKT_TYPE=${FRESHWEB_TAKT_TYPE:-balanced}
FRESHWEB_SCENE_LENGTH_MULTIPLIER=${FRESHWEB_SCENE_LENGTH_MULTIPLIER:-1.6}
FRESHWEB_SCENE_LENGTH_BIAS=${FRESHWEB_SCENE_LENGTH_BIAS:-0}

# Video mode preset
# singleImageOnly:
#   all clips use image-to-video only, no first/last-frame model
# storyDrivenMixed:
#   scene planning may choose between singleImage and firstLast
VIDEO_MODE_PRESET=${VIDEO_MODE_PRESET:-storyDrivenMixed}

case "$VIDEO_MODE_PRESET" in
  singleImageOnly)
    FRESHWEB_IMAGE_TO_VIDEO_ONLY=${FRESHWEB_IMAGE_TO_VIDEO_ONLY:-1}
    FRESHWEB_FIRST_CLIP_VIDEO_MODE=${FRESHWEB_FIRST_CLIP_VIDEO_MODE:-singleImage}
    FRESHWEB_LATER_CLIPS_SINGLE_IMAGE=${FRESHWEB_LATER_CLIPS_SINGLE_IMAGE:-1}
    FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS=${FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS:-0}
    FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE=${FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE:-0}
    ;;
  storyDrivenMixed)
    FRESHWEB_IMAGE_TO_VIDEO_ONLY=${FRESHWEB_IMAGE_TO_VIDEO_ONLY:-0}
    FRESHWEB_FIRST_CLIP_VIDEO_MODE=${FRESHWEB_FIRST_CLIP_VIDEO_MODE:-singleImage}
    FRESHWEB_LATER_CLIPS_SINGLE_IMAGE=${FRESHWEB_LATER_CLIPS_SINGLE_IMAGE:-0}
    FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS=${FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS:-1}
    FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE=${FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE:-1}
    ;;
  *)
    echo "Unknown VIDEO_MODE_PRESET: $VIDEO_MODE_PRESET" >&2
    echo "Expected: singleImageOnly or storyDrivenMixed" >&2
    exit 1
    ;;
esac

# Still-image generation
# Smaller default size for faster tuning iterations.
FRESHWEB_IMAGE_WIDTH=${FRESHWEB_IMAGE_WIDTH:-512}
FRESHWEB_IMAGE_HEIGHT=${FRESHWEB_IMAGE_HEIGHT:-384}
FRESHWEB_IMAGE_STEPS=${FRESHWEB_IMAGE_STEPS:-16}
FRESHWEB_IMAGE_GUIDANCE=${FRESHWEB_IMAGE_GUIDANCE:-3}

# First/last video settings
# Kept for compatibility, but unused while FRESHWEB_IMAGE_TO_VIDEO_ONLY=1.
FRESHWEB_VIDEO_WIDTH=${FRESHWEB_VIDEO_WIDTH:-512}
FRESHWEB_VIDEO_HEIGHT=${FRESHWEB_VIDEO_HEIGHT:-384}
FRESHWEB_VIDEO_STEPS=${FRESHWEB_VIDEO_STEPS:-24}
FRESHWEB_VIDEO_GUIDANCE=${FRESHWEB_VIDEO_GUIDANCE:-5}
FRESHWEB_VIDEO_FPS=${FRESHWEB_VIDEO_FPS:-10}
FRESHWEB_VIDEO_NUM_FRAMES=${FRESHWEB_VIDEO_NUM_FRAMES:-41}
FRESHWEB_VIDEO_CUSTOM_MAX_AREA=${FRESHWEB_VIDEO_CUSTOM_MAX_AREA:-307200}
FRESHWEB_VIDEO_RANDOMIZE_SEED=${FRESHWEB_VIDEO_RANDOMIZE_SEED:-1}

# Image-to-video settings
FRESHWEB_SINGLE_VIDEO_WIDTH=${FRESHWEB_SINGLE_VIDEO_WIDTH:-512}
FRESHWEB_SINGLE_VIDEO_HEIGHT=${FRESHWEB_SINGLE_VIDEO_HEIGHT:-384}
FRESHWEB_SINGLE_FPS=${FRESHWEB_SINGLE_FPS:-8}
FRESHWEB_VIDEO_SAMPLING_STEPS=${FRESHWEB_VIDEO_SAMPLING_STEPS:-24}
FRESHWEB_VIDEO_GUIDE_SCALE=${FRESHWEB_VIDEO_GUIDE_SCALE:-5}
FRESHWEB_VIDEO_SHIFT=${FRESHWEB_VIDEO_SHIFT:-4}

# Audio
FRESHWEB_MIRELO_STEPS=${FRESHWEB_MIRELO_STEPS:-10}
FRESHWEB_MIRELO_CREATIVITY=${FRESHWEB_MIRELO_CREATIVITY:-2.8}

# Camera
FRESHWEB_CAMERA_OUTPUT_DIR=${FRESHWEB_CAMERA_OUTPUT_DIR:-$(pwd)/../../../tests/GENERATIONS/camera-shot}

export \
  VIDEO_MODE_PRESET \
  FRESHWEB_MODE \
  FRESHWEB_WORDS \
  FRESHWEB_FOLDER \
  FRESHWEB_OPENING_PROMPT \
  FRESHWEB_SCENE_VISUAL_DIRECTION \
  FRESHWEB_USE_VISION \
  FRESHWEB_LOCK_PROMPT_CONTINUITY_TO_OPENING_FRAME \
  FRESHWEB_RESTART_FROM_PREVIOUS_MOVIE_LAST_FRAME \
  FRESHWEB_USE_TAKTMUSTER_LENGTHS \
  FRESHWEB_TAKT \
  FRESHWEB_TAKT_TYPE \
  FRESHWEB_SCENE_LENGTH_MULTIPLIER \
  FRESHWEB_SCENE_LENGTH_BIAS \
  FRESHWEB_IMAGE_TO_VIDEO_ONLY \
  FRESHWEB_FIRST_CLIP_VIDEO_MODE \
  FRESHWEB_LATER_CLIPS_SINGLE_IMAGE \
  FRESHWEB_DYNAMIC_SINGLE_IMAGE_LATER_CLIPS \
  FRESHWEB_SCENE_PLAN_CONTROLS_VIDEO_MODE \
  FRESHWEB_IMAGE_WIDTH \
  FRESHWEB_IMAGE_HEIGHT \
  FRESHWEB_IMAGE_STEPS \
  FRESHWEB_IMAGE_GUIDANCE \
  FRESHWEB_VIDEO_WIDTH \
  FRESHWEB_VIDEO_HEIGHT \
  FRESHWEB_VIDEO_STEPS \
  FRESHWEB_VIDEO_GUIDANCE \
  FRESHWEB_VIDEO_FPS \
  FRESHWEB_VIDEO_NUM_FRAMES \
  FRESHWEB_VIDEO_CUSTOM_MAX_AREA \
  FRESHWEB_VIDEO_RANDOMIZE_SEED \
  FRESHWEB_SINGLE_VIDEO_WIDTH \
  FRESHWEB_SINGLE_VIDEO_HEIGHT \
  FRESHWEB_SINGLE_FPS \
  FRESHWEB_VIDEO_SAMPLING_STEPS \
  FRESHWEB_VIDEO_GUIDE_SCALE \
  FRESHWEB_VIDEO_SHIFT \
  FRESHWEB_MIRELO_STEPS \
  FRESHWEB_MIRELO_CREATIVITY \
  FRESHWEB_CAMERA_OUTPUT_DIR

node "$(pwd)/MIX-again-freshweb.js" "$@"
